# Generated by Django 5.2 on 2025-05-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="photo",
            field=models.ImageField(default=None, null=True, upload_to="images"),
        ),
    ]
